arch: "maskrcnn"
backbone: "fpn"

optimization: "SGD"
momentum: 0.9
alter: False
lr: 2.0
lr_decay: 0.7
lr_decay_time: 300
niter: 1000

alpha: 6
lamb_norm: 1.0e-5
tv_alpha: 2
lamb_tv: 1.0e-5

blur_every: 5
blur_start: 5.0
blur_decay: 0.985
blur_end: 0.5

if_jitter: False
jitter_every: 30
jitter_x: 4
jitter_y: 4

scale_weight: [0.125, 0.5, 1.0 , 2.0 ,8.0]

rpn_cls_wei: 10.0
rpn_reg_wei: 30.0
roi_cls_wei: 10.0
roi_reg_wei: 30.0
roi_pos_wei: 1.0
roi_mask_wei: 10.0